name: Move PR To Work In Progress
on:
  pull_request_target:
    types: [labeled]
jobs:
  move-pr-to-work-in-progress:
    if: github.event.label.name == 'work in progress'
    runs-on: ubuntu-latest
    steps:
      - name: Move To Initial Review
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);
                        
            // Get list of projects and find "Code Reviews" by name
            // This does not rely on finding the project ID
            const projects = await github.rest.projects.listForRepo({
              context.repository.owner,
              context.repository
            });
            console.log(projects);
