name: Move PR To Work In Progress
on:
  issue_comment:
    types: [created]
jobs:
  move-pr-to-work-in-progress:
    if: github.event.comment.body == '/pr mark work-in-progress' && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Move To Initial Review
        uses: actions/github-script@v6
        with:
          script: |            
            // Find "Code Reviews" project manually by name matching
            // This avoids hardcoding the project ID
            const projects = await github.rest.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            const code_reviews = projects.data.find(project => {
              return project.name === 'Code Reviews';
            })
            if (code_reviews === undefined) {
              return // Should not happen, but just for safety
            }
            
            // Find "Work In Progress" column manually by name matching
            // This avoids hardcoding the project ID
            const columns = await github.rest.projects.listColumns({
              project_id: code_reviews.id,
            });
            const work_in_progress = columns.data.find(column => {
              return column.name === 'Work In Progress';
            })
            if (work_in_progress === undefined) {
              return // Should not happen, but just for safety
            }

            const cards = await github.rest.projects.listCards({
              column_id: work_in_progress.id,
            });
            console.log(cards);
            console.log(context);
