name: Move PR To Work In Progress
on:
  issues:
    types: 
      - labeled
jobs:
  move-pr-to-work-in-progress:
    if: github.event.label.name == 'work in progress'
    runs-on: ubuntu-latest
    steps:
      - name: Move To Initial Review
        uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Code Reviews
          column: Work In Progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}
