name: Move PR To Work In Progress
on:
  pull_request_target:
    types: [labeled]
jobs:
  move-pr-to-work-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move To Initial Review
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
